version: '3'
services:
  react-native:
    build:
      context: .
    #command: npx react-native run-android
    command: npx react-native start --reset-cache
    volumes:
      - .:/app
      - /dev/bus/usb:/dev/bus/usb
      - gradle:/root/.gradle # Avoid download gradle everytime
    working_dir: /app
    # network_mode: host
    ports:
      - "8081:8081"
      - "5037:5037"
      - "19000:19000"
      - "19001:19001"
    privileged: true

volumes:
  gradle:
