#require_relative '../node_modules/react-native/scripts/react_native_pods'
#require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")
require File.join(File.dirname(`node --print "require.resolve('react-native-unimodules/package.json')"`), "cocoapods")

platform :ios, '11.0'

target 'tesis' do
  use_unimodules!
  pod 'react-native-ffmpeg/min-gpl-lts', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  target 'tesisTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!() #({ 'Flipper' => '0.143.0' }) #({ 'Flipper-Folly' => '2.3.0' })
  # use_flipper! #({'Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1'})
  use_flipper!({ 'Flipper' => '0.144.0' }) 
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end

    # installer.pods_project.targets.each do |target|
    #   target.build_configurations.each do |config|
    #     if Gem::Version.new('8.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
    #       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
    #     end
    #   end
    #end
    # installer.pods_project.targets.each do |target|
    #   target.build_configurations.each do |config|
    #     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    #   end
    # end

    flipper_post_install(installer)

    # https://github.com/facebook/react-native/blob/main/scripts/react_native_pods.rb#L712
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # ensure IPHONEOS_DEPLOYMENT_TARGET is at least 11.0
        deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f
        should_upgrade = deployment_target < 11.0 && deployment_target != 0.0
        if should_upgrade
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
      end
    end
  
    # But... doing so caused another issue in Flipper:
    #   "Time.h:52:17: error: typedef redefinition with different types"
    # We need to make a patch to RCT-Folly - remove the `__IPHONE_OS_VERSION_MIN_REQUIRED` check.
    # See https://github.com/facebook/flipper/issues/834 for more details.
    time_header = "#{Pod::Config.instance.installation_root.to_s}/Pods/RCT-Folly/folly/portability/Time.h"
    `sed -i -e  $'s/ && (__IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_10_0)//' #{time_header}`
  end
end

target 'tesis-tvOS' do
  # Pods for tesis-tvOS

  target 'tesis-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
